services:
  rabbitmq:
    image: masstransit/rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
        resources:
            limits:
                cpus: '0.3'
                memory: 130M
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: RabbitMq!123
    networks:
      - local_network
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
        interval: 5s
        timeout: 5s
        retries: 5

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - local_network
    command: redis-server /etc/redis/redis.conf --save "" --appendonly no --maxclients 20000 
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'
    
  api1: &api
    build:
      context: ./src
      dockerfile: ./MandiocaCozidinha.Services.Api/Dockerfile
    hostname: api1
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 90M
    environment:
      Services__PaymentProcessor__Default: "http://payment-processor-default:8080"
      Services__PaymentProcessor__Fallback: "http://payment-processor-fallback:8080"
      Services__PaymentProcessor__Token: "123"
      RabbitMq__Uri: "rabbitmq"
      RabbitMq__User: "user"
      RabbitMq__Password: "RabbitMq!123"
      Redis__Server: "redis:6379"
    ports:
      - "9990:8080"
    networks:
      - local_network
      - payment-processor 

  api2: 
    <<: *api
    hostname: api2
    ports:
      - "9991:8080"

  nginx:
    image: nginx:latest
    networks:
      - local_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
     
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  local_network:
    driver: bridge
  payment-processor:
    external: true